# Generated by Django 4.1.7 on 2023-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategorimodel",
            options={"verbose_name": "kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AlterField(
            model_name="kategorimodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
