# Generated by Django 4.1.7 on 2023-02-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_yazilarmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YazilarModel",
        ),
    ]
