# Generated by Django 4.1.7 on 2023-02-21 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_yazilarmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yazilarmodel",
            name="icerik",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
