# Generated by Django 4.1.7 on 2023-02-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_iletisimmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yorummodel",
            old_name="guncelleme_tarihi",
            new_name="duzenlenme_tarihi",
        ),
    ]
